export default [
  {
    id: 1,
    title: "净菜",
    gimage: "http://blog.img.duanshuilu.com/nbsd4fsd45fsd5f.jpg",
    foods: [
      {
        id: 8,
        name: "雪里红",
        small_image: "http://blog.img.duanshuilu.com/sd2fsd2fsd3fsdf.jpg",
        price: 2,
        spec: "农家现摘5斤新鲜雪里蕻雪里红雪菜春不老雪里翁青菜蔬菜包邮",
        total_sales: 32265,
        body: "http://blog.img.duanshuilu.com/sd2fsd2fsd3fsdf.jpg",
        category: 1,
      },
      {
        id: 18,
        name: "攸县香干",
        small_image: "http://blog.img.duanshuilu.com/bbds5f54we455rerwe.jpg",
        price: 4,
        spec: "攸县香干238g4包软嫩湖南特产豆腐干素肉黄豆制品炒菜即食湘菜馆",
        total_sales: 2214,
        body: "http://blog.img.duanshuilu.com/bbds5f54we455rerwe.jpg",
        category: 1,
      },
      {
        id: 185,
        name: "手撕包菜",
        small_image: "http://blog.img.duanshuilu.com/10.png",
        price: 4,
        spec: "清淡饮食",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/10.png",
        category: 1,
      },
      {
        id: 186,
        name: "粉蒸肉",
        small_image: "http://blog.img.duanshuilu.com/11.png",
        price: 8,
        spec: "适合午餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/11.png",
        category: 1,
      },
      {
        id: 187,
        name: "锅包肉",
        small_image: "http://blog.img.duanshuilu.com/12.png",
        price: 8,
        spec: "适合午餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/12.png",
        category: 1,
      },
      {
        id: 188,
        name: "红烧牛肉",
        small_image: "http://blog.img.duanshuilu.com/13.png",
        price: 12,
        spec: "适合晚餐 时间要充裕奥",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/13.png",
        category: 1,
      },
      {
        id: 189,
        name: "辣子鸡",
        small_image: "http://blog.img.duanshuilu.com/14.png",
        price: 12,
        spec: "川味十足",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/14.png",
        category: 1,
      },
      {
        id: 190,
        name: "牛肉炖土豆",
        small_image: "http://blog.img.duanshuilu.com/15.png",
        price: 12,
        spec: "量足实惠",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/15.png",
        category: 1,
      },
      {
        id: 191,
        name: "糖醋鲤鱼",
        small_image: "http://blog.img.duanshuilu.com/16.png",
        price: 18,
        spec: "味极鲜",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/16.png",
        category: 1,
      },
      {
        id: 200,
        name: "木须肉",
        small_image: "http://blog.img.duanshuilu.com/17.png",
        price: 6,
        spec: "鸡蛋 泡发木耳 黄瓜 腌制鸡肉片 适合午餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/17.png",
        category: 1,
      },
    ],
  },
  {
    id: 2,
    title: "净菜搭配",
    gimage: "http://blog.img.duanshuilu.com/sda8f8sd8fsd88ds8fe8wr8ew8r8ew.jpg",
    foods: [
      {
        id: 167,
        name: "酸菜鱼",
        small_image:
          "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_17-53-34.png",
        price: 24,
        spec: "新鲜上市，处理方便，新手友好",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_17-53-34.png",
        category: 2,
      },
      {
        id: 168,
        name: "红烧鸡翅",
        small_image:
          "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_17-56-00.png",
        price: 18,
        spec: "方便上手，鸡翅处理好，酱料搭配好",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_17-56-00.png",
        category: 2,
      },
      {
        id: 169,
        name: "凉拌藕片",
        small_image:
          "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_17-57-13.png",
        price: 8,
        spec: "适合早餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_17-57-13.png",
        category: 2,
      },
      {
        id: 170,
        name: "西红柿炒蛋",
        small_image:
          "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_17-58-47.png",
        price: 6,
        spec: "适合午餐，简单方便",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_17-58-47.png",
        category: 2,
      },
      {
        id: 171,
        name: "红烧笋干",
        small_image:
          "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_18-00-47.png",
        price: 12,
        spec: "方便上手，适合晚餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/Snipaste_2021-10-31_18-00-47.png",
        category: 2,
      },
      {
        id: 178,
        name: "酸辣土豆丝",
        small_image: "http://blog.img.duanshuilu.com/5.png",
        price: 6,
        spec: "土豆丝 蒜 调味包 适合午晚餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/5.png",
        category: 2,
      },
      {
        id: 179,
        name: "鱼香茄子",
        small_image: "http://blog.img.duanshuilu.com/6.png",
        price: 7,
        spec: "茄子 鱼香调味包 油 盐 适合午晚餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/6.png",
        category: 2,
      },
      {
        id: 180,
        name: "啤酒鸭",
        small_image: "http://blog.img.duanshuilu.com/7.png",
        price: 7,
        spec: "鸭块 啤酒 油 盐 适合午晚餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/7.png",
        category: 2,
      },
      {
        id: 181,
        name: "麻婆豆腐",
        small_image: "http://blog.img.duanshuilu.com/8.png",
        price: 4,
        spec: "豆腐 红油 耗油 适合三餐",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/8.png",
        category: 2,
      },
      {
        id: 182,
        name: "宫保鸡丁",
        small_image: "http://blog.img.duanshuilu.com/9.png",
        price: 12,
        spec: "主料鸡肉 简单易上手",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/9.png",
        category: 2,
      },
    ],
  },
  {
    id: 3,
    title: "水产海鲜",
    gimage: "http://blog.img.duanshuilu.com/8ds8fds88dfs8ds8fds88fds8dfs.png",
    foods: [
      {
        id: 62,
        name: "4斤整箱虾",
        small_image:
          "http://blog.img.duanshuilu.com/ds2f2dsf2d2sf2ds2fds2f.png",
        price: 389,
        spec: "4斤整箱虾鲜活海鲜水产超大虾基围虾鲜虾特大海虾速冻青大虾冻虾",
        total_sales: 3326,
        body: "http://blog.img.duanshuilu.com/ds2f2dsf2d2sf2ds2fds2f.png",
        category: 3,
      },
      {
        id: 63,
        name: "5斤约50条银鲳鱼",
        small_image:
          "http://blog.img.duanshuilu.com/efddfdssdfsdf26ds6fds23f3dsf23dssdffsd.jpg",
        price: 569,
        spec: "5斤约50条银鲳鱼中号白鲳鱼新鲜海捕冰鲜冷冻整箱海鲜水产",
        total_sales: 22156,
        body:
          "http://blog.img.duanshuilu.com/efddfdssdfsdf26ds6fds23f3dsf23dssdffsd.jpg",
        category: 3,
      },
      {
        id: 65,
        name: "乳山生蚝鲜活",
        small_image:
          "http://blog.img.duanshuilu.com/sda9f8dsafdsa9f8as9dfdsaf.jpg",
        price: 254,
        spec: "乳山生蚝鲜活10特大牡蛎带壳生吃海蛎子新鲜海鲜水产5斤一箱顺丰",
        total_sales: 33256,
        body: "http://blog.img.duanshuilu.com/sda9f8dsafdsa9f8as9dfdsaf.jpg",
        category: 3,
      },
      {
        id: 69,
        name: "即食鲍鱼",
        small_image:
          "http://blog.img.duanshuilu.com/SDFDSF5DS4AF45D4SF5SDAF.png",
        price: 254,
        spec: "康悦堂正宗福建佛跳墙加热即食鲍鱼海参原材料海鲜大礼包礼盒盆菜",
        total_sales: 3326,
        body: "http://blog.img.duanshuilu.com/SDFDSF5DS4AF45D4SF5SDAF.png",
        category: 3,
      },
      {
        id: 146,
        name: "正宗黄花鱼",
        small_image:
          "http://blog.img.duanshuilu.com/8ds8fds88dfs8ds8fds88fds8dfs.png",
        price: 89,
        spec: "4斤超大正宗黄花鱼新鲜冷冻宁德黄瓜鱼整箱生鲜活海鱼野生大黄鱼",
        total_sales: 32323,
        body: "http://blog.img.duanshuilu.com/8ds8fds88dfs8ds8fds88fds8dfs.png",
        category: 3,
      },
      {
        id: 147,
        name: "湛江大马鲛鱼",
        small_image:
          "http://blog.img.duanshuilu.com/dsf2drsf4d1f4sd44rewrwerewr.jpg",
        price: 89,
        spec: "5斤湛江大马鲛鱼片深海鱼冷冻鱼海鱼切片鲜活大鲅鱼中段新鲜",
        total_sales: 55545,
        body: "http://blog.img.duanshuilu.com/dsf2drsf4d1f4sd44rewrwerewr.jpg",
        category: 3,
      },
      {
        id: 150,
        name: "野生银鲳鱼",
        small_image:
          "http://blog.img.duanshuilu.com/sd2d22d2fds85f8ds5f5dsfds4dsf1.jpg",
        price: 256,
        spec: "海捕野生银鲳鱼5斤鲜活海鲜冷冻白鲳鱼新鲜水产平鱼镜鱼海鱼扁鱼",
        total_sales: 22111,
        body:
          "http://blog.img.duanshuilu.com/sd2d22d2fds85f8ds5f5dsfds4dsf1.jpg",
        category: 3,
      },
      {
        id: 151,
        name: "真正舟山小黄鱼",
        small_image:
          "http://blog.img.duanshuilu.com/555sd5f5ds5fs5f5dsf5ds5fds5f5dssd5f.jpg",
        price: 98,
        spec: "真正舟山小黄鱼深海野生海鱼小黄花鱼生鲜海鲜水产新鲜冷冻烧烤",
        total_sales: 32221,
        body:
          "http://blog.img.duanshuilu.com/555sd5f5ds5fs5f5dsf5ds5fds5f5dssd5f.jpg",
        category: 3,
      },
      {
        id: 192,
        name: "土豆块",
        small_image: "http://blog.img.duanshuilu.com/9999999999999989898.jpg",
        price: 3,
        spec: "一斤量",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/9999999999999989898.jpg",
        category: 3,
      },
      {
        id: 194,
        name: "东北旱黄瓜",
        small_image: "http://blog.img.duanshuilu.com/adsf5sd5f5sdf5ds5f.jpg",
        price: 5,
        spec: "新鲜青瓜5斤顺丰发农家生吃蘸酱菜新鲜蔬菜青菜小黄瓜",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/adsf5sd5f5sdf5ds5f.jpg",
        category: 3,
      },
      {
        id: 195,
        name: "卷心芥菜",
        small_image: "http://blog.img.duanshuilu.com/aas2df2sdf2sed.jpg",
        price: 5,
        spec: "农家自种新鲜蔬菜卷心芥菜现摘5斤",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/aas2df2sdf2sed.jpg",
        category: 3,
      },
      {
        id: 197,
        name: "芹菜",
        small_image: "http://blog.img.duanshuilu.com/bbsdfesfsd2fd2f.png",
        price: 5,
        spec: "农家自种新鲜时令蔬菜芹菜4斤",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/bbsdfesfsd2fd2f.png",
        category: 3,
      },
      {
        id: 198,
        name: "菜苔棒棒",
        small_image: "http://blog.img.duanshuilu.com/bbds5f4sd5f54sdfsd.jpg",
        price: 8,
        spec: "四川新鲜菜苔棒棒5斤",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/bbds5f4sd5f54sdfsd.jpg",
        category: 3,
      },
      {
        id: 199,
        name: "苏子叶",
        small_image: "http://blog.img.duanshuilu.com/nbsd4fsd45fsd5f.jpg",
        price: 8,
        spec: "苏子叶新鲜食用包饭500g",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/nbsd4fsd45fsd5f.jpg",
        category: 3,
      },
    ],
  },
  {
    id: 4,
    title: "新鲜水果",
    gimage: "http://blog.img.duanshuilu.com/d23f2sd2fds2f2ds2fds2f.jpg",
    foods: [
      {
        id: 44,
        name: "橙子",
        small_image:
          "http://blog.img.duanshuilu.com/td3fs2dsf3sdfgdsffsdf3sd.jpg",
        price: 10,
        spec: "10斤现摘四川爱媛38号果冻橙大果新鲜水果整箱手剥应季橙子",
        total_sales: 55986,
        body: "http://blog.img.duanshuilu.com/td3fs2dsf3sdfgdsffsdf3sd.jpg",
        category: 4,
      },
      {
        id: 45,
        name: "富士苹果",
        small_image: "http://blog.img.duanshuilu.com/p2sd12fsd1fsd12fs.jpg",
        price: 12,
        spec: "芭芭农场专用兑换品冰糖心富士苹果3斤",
        total_sales: 300,
        body: "http://blog.img.duanshuilu.com/p2sd12fsd1fsd12fs.jpg",
        category: 4,
      },
      {
        id: 46,
        name: "四季红颜草梅",
        small_image:
          "http://blog.img.duanshuilu.com/csdfdsfdsfds32fds323fsd3sd3dffsdf.jpg",
        price: 13,
        spec: "丹东99牛奶草莓3斤新鲜应当季水果整箱包邮孕妇奶油四季红颜草梅",
        total_sales: 30000,
        body:
          "http://blog.img.duanshuilu.com/csdfdsfdsfds32fds323fsd3sd3dffsdf.jpg",
        category: 4,
      },
      {
        id: 47,
        name: "库尔勒香梨",
        small_image: "http://blog.img.duanshuilu.com/ds7sd7f7sd7f7dsf.jpg",
        price: 20,
        spec: "东方葵园新疆库尔勒香梨单果120g24粒装当季新鲜现摘整箱包邮",
        total_sales: 9984,
        body: "http://blog.img.duanshuilu.com/ds7sd7f7sd7f7dsf.jpg",
        category: 4,
      },
      {
        id: 48,
        name: "广西百香果",
        small_image:
          "http://blog.img.duanshuilu.com/sdf2sdfsd23f3s2df3sd3f3sdf3sdf.jpg",
        price: 89,
        spec: "广西百香果大果5斤包邮水果新鲜白百果香果酱浆汁2一级当季整箱10",
        total_sales: 33325,
        body:
          "http://blog.img.duanshuilu.com/sdf2sdfsd23f3s2df3sd3f3sdf3sdf.jpg",
        category: 4,
      },
      {
        id: 49,
        name: "红心火龙果",
        small_image: "http://blog.img.duanshuilu.com/sdfsdfdsfdsfdsfdsf.jpg",
        price: 30,
        spec: "海南红心火龙果5斤金都一号新鲜当季水果大果红肉10整箱一级包邮",
        total_sales: 22569,
        body: "http://blog.img.duanshuilu.com/sdfsdfdsfdsfdsfdsf.jpg",
        category: 4,
      },
      {
        id: 50,
        name: "红富士苹果",
        small_image: "http://blog.img.duanshuilu.com/asdfsdfsdfs222222sdf.jpg",
        price: 18,
        spec: "红富士苹果水果10斤新鲜当季陕西一整箱批发应季丑苹果脆甜包邮",
        total_sales: 223336,
        body: "http://blog.img.duanshuilu.com/asdfsdfsdfs222222sdf.jpg",
        category: 4,
      },
      {
        id: 51,
        name: "江西赣南脐橙",
        small_image:
          "http://blog.img.duanshuilu.com/sdfsdlfdsfdsjfkd77778dsf.jpg",
        price: 20,
        spec: "江西赣南脐橙10斤整箱新鲜水果当季甜橙20应季果冻橙子大果包邮",
        total_sales: 22456,
        body: "http://blog.img.duanshuilu.com/sdfsdlfdsfdsjfkd77778dsf.jpg",
        category: 4,
      },
      {
        id: 52,
        name: "柚子",
        small_image:
          "http://blog.img.duanshuilu.com/s3d3f3sdfs5dfdsf5dsf5sdf.jpg",
        price: 30,
        spec: "精品20斤正宗玉环文旦柚子浙江台州楚门应当季新鲜水果蜜柚非红心",
        total_sales: 22145,
        body: "http://blog.img.duanshuilu.com/s3d3f3sdfs5dfdsf5dsf5sdf.jpg",
        category: 4,
      },
      {
        id: 155,
        name: "淡雪白草莓",
        small_image:
          "http://blog.img.duanshuilu.com/dsf2sd2fsd2fsdfw5fdsfdsfsdf8sdf.jpg",
        price: 69,
        spec: "淡雪白草莓礼盒牛奶奶油新鲜孕妇当季水果非日本进口淡雪白色圣诞",
        total_sales: 665656,
        body:
          "http://blog.img.duanshuilu.com/dsf2sd2fsd2fsdfw5fdsfdsfsdf8sdf.jpg",
        category: 4,
      },
      {
        id: 156,
        name: "猫山王榴莲",
        small_image:
          "http://blog.img.duanshuilu.com/6d6sf9wer9ew9ds66dsfdfdsf.jpg",
        price: 189,
        spec: "稻甜马来西亚猫山王榴莲新鲜进口水果冷冻保鲜D197整果顺丰包邮",
        total_sales: 2215,
        body: "http://blog.img.duanshuilu.com/6d6sf9wer9ew9ds66dsfdfdsf.jpg",
        category: 4,
      },
      {
        id: 157,
        name: "进口牛油果",
        small_image:
          "http://blog.img.duanshuilu.com/2sd2f2ds2f2f5erertewewrewr.jpg",
        price: 78,
        spec: "甘福园墨西哥进口牛油果10个装新鲜当季水果鳄梨整箱应季批发包邮",
        total_sales: 8856,
        body: "http://blog.img.duanshuilu.com/2sd2f2ds2f2f5erertewewrewr.jpg",
        category: 4,
      },
      {
        id: 158,
        name: "智利车厘子",
        small_image:
          "http://blog.img.duanshuilu.com/d23f2sd2fds2f2ds2fds2f.jpg",
        price: 658,
        spec: "盒马智利车厘子净重25kg单果JJ进口水果樱桃当季时令新鲜水果",
        total_sales: 44452,
        body: "http://blog.img.duanshuilu.com/d23f2sd2fds2f2ds2fds2f.jpg",
        category: 4,
      },
      {
        id: 160,
        name: "进口椰青",
        small_image:
          "http://blog.img.duanshuilu.com/sadfsafdasdffsd9sd9fs9df9dsf9ds9f8ds8fdssd.png",
        price: 89,
        spec: "泰国进口椰青700g6个去皮青香水椰子应当季新鲜孕妇水果整箱送礼",
        total_sales: 2222125,
        body:
          "http://blog.img.duanshuilu.com/sadfsafdasdffsd9sd9fs9df9dsf9ds9f8ds8fdssd.png",
        category: 4,
      },
      {
        id: 161,
        name: "蜜柚红心柚",
        small_image:
          "http://blog.img.duanshuilu.com/ds5sdf5d5sf5ds5f5d2fds2fds02f.jpg",
        price: 68,
        spec: "2020福建平和琯溪蜜柚红心柚新鲜当季水果柚子净重85斤",
        total_sales: 22145,
        body:
          "http://blog.img.duanshuilu.com/ds5sdf5d5sf5ds5f5d2fds2fds02f.jpg",
        category: 4,
      },
      {
        id: 162,
        name: "猕猴桃",
        small_image:
          "http://blog.img.duanshuilu.com/ds3f3ds3fd6sf6ds3fsdfsdfsd.jpg",
        price: 56,
        spec: "芭芭农场陕西徐香猕猴桃12粒单果80g奇异果当季新鲜水果包邮",
        total_sales: 55896,
        body: "http://blog.img.duanshuilu.com/ds3f3ds3fd6sf6ds3fsdfsdfsd.jpg",
        category: 4,
      },
    ],
  },
  {
    id: 5,
    title: "美味饮料",
    gimage: "http://blog.img.duanshuilu.com/e22ew2we2ew2ew2ew.jpg",
    foods: [
      {
        id: 71,
        name: "雀巢脱脂牛奶",
        small_image: "http://blog.img.duanshuilu.com/qq3q33d3sf3ds3f.jpg",
        price: 189,
        spec: "包邮雀巢脱脂牛奶1L2盒打奶泡甜品西点奶茶蛋糕调制乳品烘焙原料",
        total_sales: 22013,
        body: "http://blog.img.duanshuilu.com/qq3q33d3sf3ds3f.jpg",
        category: 5,
      },
      {
        id: 73,
        name: "福瑞达乳酸链球菌素乳品饮料",
        small_image: "http://blog.img.duanshuilu.com/t33d333d33df33fd.jpg",
        price: 36,
        spec: "福瑞达乳酸链球菌素乳品饮料烘焙肉食休闲食品防腐防霉500g",
        total_sales: 33302,
        body: "http://blog.img.duanshuilu.com/t33d333d33df33fd.jpg",
        category: 5,
      },
      {
        id: 120,
        name: "烘焙乳品冰激凌",
        small_image:
          "http://blog.img.duanshuilu.com/sdafdf323d3sf3ds3fdssdfdsaf.jpg",
        price: 66,
        spec: "花帝HD5增香剂粉末食品用香精500g卤味烘焙乳品冰激凌肉类糖果",
        total_sales: 54565,
        body: "http://blog.img.duanshuilu.com/sdafdf323d3sf3ds3fdssdfdsaf.jpg",
        category: 5,
      },
      {
        id: 122,
        name: "西班牙进口全脂纯牛奶",
        small_image:
          "http://blog.img.duanshuilu.com/sdfew333ds3fdsfdsdsfdfsfds.jpg",
        price: 254,
        spec: "西班牙进口全脂纯牛奶1升营养早餐奶牛初乳品烘焙糕点餐饮奶茶店",
        total_sales: 2213,
        body: "http://blog.img.duanshuilu.com/sdfew333ds3fdsfdsdsfdfsfds.jpg",
        category: 5,
      },
    ],
  },
  {
    id: 6,
    title: "快手菜",
    gimage:
      "http://blog.img.duanshuilu.com/sdafrfd3a3sd3f3sdf3sd3afwafefds.jpg",
    foods: [
      {
        id: 75,
        name: "糯米煎饼",
        small_image:
          "http://blog.img.duanshuilu.com/safsgfsfsdfs3d3dsf3sd3fdsf.jpg",
        price: 18,
        spec: "爱稞紫米饼血糯米煎饼早餐速食速冻食品糯米饭早饭冷冻面饼煎饼",
        total_sales: 336,
        body: "http://blog.img.duanshuilu.com/safsgfsfsdfs3d3dsf3sd3fdsf.jpg",
        category: 6,
      },
      {
        id: 76,
        name: "烧麦",
        small_image: "http://blog.img.duanshuilu.com/x33x33x33f33x3f.jpg",
        price: 25,
        spec: "正大糯米猪肉烧卖600g24只装烧麦速冻食品早点烧麦广式点心小吃",
        total_sales: 22215,
        body: "http://blog.img.duanshuilu.com/x33x33x33f33x3f.jpg",
        category: 6,
      },
      {
        id: 77,
        name: "窝窝头",
        small_image:
          "http://blog.img.duanshuilu.com/sfs2rg22as2r2f2fds22dsa2fsdf.jpg",
        price: 23,
        spec: "杂粮包玉米小窝窝头早餐食品主食粗粮半成品速冻面食营养包邮60个",
        total_sales: 22654,
        body: "http://blog.img.duanshuilu.com/sfs2rg22as2r2f2fds22dsa2fsdf.jpg",
        category: 6,
      },
      {
        id: 78,
        name: "玉米饼",
        small_image:
          "http://blog.img.duanshuilu.com/2ds2f2sad2few55r55s5fsdfdfsfds.jpg",
        price: 26,
        spec: "玉米饼四师姐早点蒸煎饼半成品速冻食品广式点心12个包",
        total_sales: 33365,
        body:
          "http://blog.img.duanshuilu.com/2ds2f2sad2few55r55s5fsdfdfsfds.jpg",
        category: 6,
      },
      {
        id: 79,
        name: "包子",
        small_image:
          "http://blog.img.duanshuilu.com/sdafrfd3a3sd3f3sdf3sd3afwafefds.jpg",
        price: 36,
        spec: "一旬一味墨鱼瑶柱手工馄饨大海鲜混沌面食速冻冷方便食品云吞",
        total_sales: 22236,
        body:
          "http://blog.img.duanshuilu.com/sdafrfd3a3sd3f3sdf3sd3afwafefds.jpg",
        category: 6,
      },
      {
        id: 80,
        name: "水晶饺子",
        small_image:
          "http://blog.img.duanshuilu.com/ds3f3sd3f3we3ewr3w3er3ewr.jpg",
        price: 39,
        spec: "水晶饺子港式点心早茶休闲点心潮汕粉粿450g10个速冻食品",
        total_sales: 22145,
        body: "http://blog.img.duanshuilu.com/ds3f3sd3f3we3ewr3w3er3ewr.jpg",
        category: 6,
      },
    ],
  },
  {
    id: 7,
    title: "营养早餐",
    gimage: "http://blog.img.duanshuilu.com/dfssdfsdfsdfd2121ds21f.png",
    foods: [
      {
        id: 173,
        name: "凉拌黄瓜",
        small_image: "http://blog.img.duanshuilu.com/2.png",
        price: 4,
        spec: "早餐易上手",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/2.png",
        category: 7,
      },
      {
        id: 174,
        name: "小葱拌豆腐",
        small_image: "http://blog.img.duanshuilu.com/1.png",
        price: 3,
        spec: "口味清淡,早餐易上手",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/1.png",
        category: 7,
      },
      {
        id: 176,
        name: "冰镇酸辣蜇头",
        small_image: "http://blog.img.duanshuilu.com/3.png",
        price: 6,
        spec: "海蜇 醋包 调味 红青椒",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/3.png",
        category: 7,
      },
      {
        id: 177,
        name: "凉拌裙带菜",
        small_image: "http://blog.img.duanshuilu.com/4.png",
        price: 6,
        spec: "裙带菜 味精 调味 香菜",
        total_sales: 0,
        body: "http://blog.img.duanshuilu.com/4.png",
        category: 7,
      },
    ],
  },
];
